import type { Metadata } from "next";
import { Poppins, Open_Sans, Montserrat } from "next/font/google";
import "./globals.css";

import { Sidebar } from "@/components/layout/sidebar";
import SiteHeader from "@/components/layout/site-header";

const font = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "100", "200", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="flex w-full m-auto">
          <Sidebar className="lg:flex-[0.15]" />
          <div className="flex-1 lg:border-l flex flex-col max-h-screen overflow-scroll">
            <SiteHeader />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
